# Generated by Django 5.2.17 on 2026-09-08 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(help_text="Git repository URL", max_length=500),
                ),
                (
                    "provider",
                    models.CharField(
                        default="github",
                        help_text="VCS Provider (github, gitlab, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "pr_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Pull Request / Merge Request number",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("INGESTING", "Ingesting"),
                            ("INGESTED", "Ingested"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        help_text="Current execution status of the run",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Verification Run",
                "verbose_name_plural": "Verification Runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
