# Generated by Django 5.2.17 on 2026-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrun",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error details if verification run failed",
            ),
        ),
        migrations.AddField(
            model_name="verificationrun",
            name="ingestion_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Normalized PR and diff metadata"
            ),
        ),
    ]
