# Generated by Django 5.2.17 on 2026-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0002_verificationrun_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrun",
            name="findings",
            field=models.JSONField(
                blank=True, default=list, help_text="Negative-space scanner findings"
            ),
        ),
        migrations.AlterField(
            model_name="verificationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("INGESTING", "Ingesting"),
                    ("INGESTED", "Ingested"),
                    ("SCANNING", "Scanning"),
                    ("SCANNED", "Scanned"),
                    ("SCAN_FAILED", "Scan Failed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                help_text="Current execution status of the run",
                max_length=20,
            ),
        ),
    ]
