# Generated by Django 5.2.17 on 2026-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0003_verificationrun_findings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrun",
            name="architecture_findings",
            field=models.JSONField(
                blank=True, default=list, help_text="Architecture fit checker findings"
            ),
        ),
        migrations.AlterField(
            model_name="verificationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("INGESTING", "Ingesting"),
                    ("INGESTED", "Ingested"),
                    ("SCANNING", "Scanning"),
                    ("SCANNED", "Scanned"),
                    ("SCAN_FAILED", "Scan Failed"),
                    ("CHECKING_ARCHITECTURE", "Checking Architecture"),
                    ("ARCHITECTURE_CHECKED", "Architecture Checked"),
                    ("ARCHITECTURE_FAILED", "Architecture Failed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                help_text="Current execution status of the run",
                max_length=30,
            ),
        ),
    ]
