# Generated by Django 5.2.17 on 2026-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0004_verificationrun_architecture_findings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrun",
            name="confidence_score",
            field=models.IntegerField(
                blank=True, help_text="Confidence score 0-100", null=True
            ),
        ),
        migrations.AddField(
            model_name="verificationrun",
            name="score_breakdown",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Detailed penalty breakdown for confidence score",
            ),
        ),
        migrations.AddField(
            model_name="verificationrun",
            name="score_explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Explanation of confidence score calculation",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("INGESTING", "Ingesting"),
                    ("INGESTED", "Ingested"),
                    ("SCANNING", "Scanning"),
                    ("SCANNED", "Scanned"),
                    ("SCAN_FAILED", "Scan Failed"),
                    ("CHECKING_ARCHITECTURE", "Checking Architecture"),
                    ("ARCHITECTURE_CHECKED", "Architecture Checked"),
                    ("ARCHITECTURE_FAILED", "Architecture Failed"),
                    ("SCORING", "Scoring"),
                    ("SCORED", "Scored"),
                    ("SCORE_FAILED", "Score Failed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                help_text="Current execution status of the run",
                max_length=30,
            ),
        ),
    ]
