# Generated by Django 5.2.17 on 2026-09-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0005_verificationrun_confidence_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        help_text="Pipeline event or stage name", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Status of event (SUCCESS, FAILED, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sanitized event details and context",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when audit log was recorded",
                    ),
                ),
                (
                    "verification_run",
                    models.ForeignKey(
                        help_text="Associated verification run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="verification.verificationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["timestamp"],
            },
        ),
    ]
